# produtos_config.py

PRODUTOS = {
    "SEGUNDA-FEIRA": [
        {'nome': 'Banana Nanica (Teste)', 'unidade_fracionada': 'KG', 'codigo_interno': '999992'},
        {'nome': 'Laranja Pera (Teste)', 'unidade_fracionada': 'KG', 'codigo_interno': '999993'},
        {'nome': 'Maçã Fuji (Teste)', 'unidade_fracionada': 'KG', 'codigo_interno': '999991'}
    ],
    "QUINTA-FEIRA": [
        {'nome': 'PRODUTO TESTE QUINTA 1', 'unidade_fracionada': 'KG', 'codigo_interno': '888881'},
        {'nome': 'PRODUTO TESTE QUINTA 2', 'unidade_fracionada': 'UN', 'codigo_interno': '888882'},
        {'nome': 'PRODUTO TESTE QUINTA 3', 'unidade_fracionada': 'KG', 'codigo_interno': '888883'}
    ],
    "TERÇA-FEIRA": [
        {'nome': 'ABACATE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310100'},
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN', 'codigo_interno': '311283'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN', 'codigo_interno': '352544'},
        {'nome': 'ALHO EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310289'},
        {'nome': 'ALHO S CASCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310108'},
        {'nome': 'AMEIXA IMPORTADA 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '330803'},
        {'nome': 'AMEIXA KG IMPORTADA', 'unidade_fracionada': 'KG', 'codigo_interno': '310109'},
        {'nome': 'AMEIXA KG NACIONAL', 'unidade_fracionada': 'KG', 'codigo_interno': '340139'},
        {'nome': 'ATEMOIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '350989'},
        {'nome': 'BANANA DA TERRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310113'},
        {'nome': 'BANANA MAÇA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310110'},
        {'nome': 'BANANA NANICA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310178'},
        {'nome': 'BANANA OURO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310111'},
        {'nome': 'BANANA PRATA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310112'},
        {'nome': 'BATATA DOCE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310115'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG', 'codigo_interno': '310119'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG', 'codigo_interno': '310173'},
        {'nome': 'CAJU 300G', 'unidade_fracionada': 'UN', 'codigo_interno': '375291'},
        {'nome': 'CAQUI 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '331637'},
        {'nome': 'CAQUI KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310124'},
        {'nome': 'CARAMBOLA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322345'},
        {'nome': 'CASTANHA PORTUGUESA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310244'},
        {'nome': 'CEREJA CHERRIES KG', 'unidade_fracionada': 'KG', 'codigo_interno': '313634'},
        {'nome': 'COCO SECO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310128'},
        {'nome': 'COCO VERDE', 'unidade_fracionada': 'UN', 'codigo_interno': '310041'},
        {'nome': 'GOIABA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310130'},
        {'nome': 'GRAVIOLA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334824'},
        {'nome': 'INHAME KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310131'},
        {'nome': 'KIWI 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '332166'},
        {'nome': 'KIWI KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310133'},
        {'nome': 'LARANJA BAHIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310134'},
        {'nome': 'LARANJA LIMA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310135'},
        {'nome': 'LARANJA PERA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310136'},
        {'nome': 'LIMA DA PERSIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310180'},
        {'nome': 'LIMÃO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310138'},
        {'nome': 'LIMÃO SICILIANO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334823'},
        {'nome': 'MAÇÃ ARGENTINA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310174'},
        {'nome': 'MAÇÃ FUJI KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310140'},
        {'nome': 'MAÇÃ GALA NACIONAL KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310211'},
        {'nome': 'MAÇÃ VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310139'},
        {'nome': 'MAMÃO AMAZONAS KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310142'},
        {'nome': 'MAMÃO FORMOSA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310175'},
        {'nome': 'MANDIOCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310143'},
        {'nome': 'MANGA PALMER KG', 'unidade_fracionada': 'KG', 'codigo_interno': '375054'},
        {'nome': 'MANGA TOMMY KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310144'},
        {'nome': 'MANGA UBA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310146'},
        {'nome': 'MARACUJÁ KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310147'},
        {'nome': 'MELANCIA BABY KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322436'},
        {'nome': 'MELANCIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310148'},
        {'nome': 'MELÃO AMARELO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310149'},
        {'nome': 'MELÃO REDINHA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322437'},
        {'nome': 'MELÃO SAPIEL KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310240'},
        {'nome': 'MEXERICA DEKOPON KG', 'unidade_fracionada': 'KG', 'codigo_interno': '374252'},
        {'nome': 'MEXERICA MORCOT KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310150'},
        {'nome': 'MEXERICA PONKAN KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310152'},
        {'nome': 'MEXERICA RIO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310151'},
        {'nome': 'MORANGA JAPONESA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310155'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '324846'},
        {'nome': 'NECTARINA KG IMPORTADA', 'unidade_fracionada': 'KG', 'codigo_interno': '340135'},
        {'nome': 'NECTARINA KG NACIONAL', 'unidade_fracionada': 'KG', 'codigo_interno': '310107'},
        {'nome': 'NOZES C CASCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310181'},
        {'nome': 'PERA PORTUGUESA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322361'},
        {'nome': 'PERA WILLIAN KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310156'},
        {'nome': 'PESSEGO BELLE FRUTA 600G', 'unidade_fracionada': 'UN', 'codigo_interno': '374794'},
        {'nome': 'PESSEGO IMPORTADO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310159'},
        {'nome': 'PESSEGO KG NACIONAL', 'unidade_fracionada': 'KG', 'codigo_interno': '310158'},
        {'nome': 'PITAYA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '364058'},
        {'nome': 'SIRIGUELA 600G', 'unidade_fracionada': 'UN', 'codigo_interno': '330115'},
        {'nome': 'UVA ITALIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310167'},
        {'nome': 'UVA NIAGARA 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '360434'},
        {'nome': 'UVA NIAGARA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310170'},
        {'nome': 'UVA PRETA S SEMENTE 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '368980'},
        {'nome': 'UVA RED GLOBE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310169'},
        {'nome': 'UVA RUBI KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310166'},
        {'nome': 'UVA S/ SEMENTE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310171'},
        {'nome': 'UVA VERDE S/ SEMENTE 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '375418'},
    ],
    "QUARTA-FEIRA": [
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN', 'codigo_interno': '311283'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN', 'codigo_interno': '352544'},
        {'nome': 'ABOBORA KG BAIANA', 'unidade_fracionada': 'KG', 'codigo_interno': '310101'},
        {'nome': 'ABOBRINHA VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310103'},
        {'nome': 'ALHO EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310289'},
        {'nome': 'ALHO S CASCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310108'},
        {'nome': 'BATATA ASTERIX KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310214'},
        {'nome': 'BATATA BAROA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310114'},
        {'nome': 'BATATA DOCE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310115'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG', 'codigo_interno': '310119'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG', 'codigo_interno': '310173'},
        {'nome': 'BATATA YACON KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334978'},
        {'nome': 'BERINJELA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310121'},
        {'nome': 'BETERRABA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310122'},
        {'nome': 'CEBOLA BRANCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310125'},
        {'nome': 'CEBOLA ROXA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334535'},
        {'nome': 'CENOURA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310126'},
        {'nome': 'CHUCHU KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310127'},
        {'nome': 'COUVE FLOR UN', 'unidade_fracionada': 'UN', 'codigo_interno': '313507'},
        {'nome': 'ERVILHA BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '310085'},
        {'nome': 'ERVILHA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310129'},
        {'nome': 'GENGIBRE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322470'},
        {'nome': 'GOIABA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310130'},
        {'nome': 'INHAME KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310131'},
        {'nome': 'JILO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310132'},
        {'nome': 'LARANJA BAHIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310134'},
        {'nome': 'LARANJA LIMA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310135'},
        {'nome': 'LARANJA PERA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310136'},
        {'nome': 'MANDIOCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310143'},
        {'nome': 'MILHO VERDE BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '312655'},
        {'nome': 'MILHO VERDE ESPIGA', 'unidade_fracionada': 'UN', 'codigo_interno': '310153'},
        {'nome': 'MORANGA JAPONESA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310155'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '324846'},
        {'nome': 'PEPINO JAPONES KG', 'unidade_fracionada': 'KG', 'codigo_interno': '345140'},
        {'nome': 'PEPINO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310154'},
        {'nome': 'PIMENTAO COLORIDO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '312952'},
        {'nome': 'PIMENTAO VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310160'},
        {'nome': 'QUIABO 300G', 'unidade_fracionada': 'UN', 'codigo_interno': '310161'},
        {'nome': 'REPOLHO ROXO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310163'},
        {'nome': 'REPOLHO VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310162'},
        {'nome': 'TOMATE CEREJA 200G', 'unidade_fracionada': 'UN', 'codigo_interno': '310237'},
        {'nome': 'TOMATE EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310165'},
        {'nome': 'VAGEM 250G', 'unidade_fracionada': 'UN', 'codigo_interno': '375105'},
        {'nome': 'VAGEM KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310172'},
    ],
    "SEXTA-FEIRA": [
        {'nome': 'ABACATE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310100'},
        {'nome': 'ALHO EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310289'},
        {'nome': 'ALHO S CASCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310108'},
        {'nome': 'BANANA NANICA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310178'},
        {'nome': 'BANANA PRATA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310112'},
        {'nome': 'BATATA ASTERIX KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310214'},
        {'nome': 'BATATA DOCE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310115'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG', 'codigo_interno': '310119'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG', 'codigo_interno': '310173'},
        {'nome': 'CAJU KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310221'},
        {'nome': 'LARANJA PERA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310136'},
        {'nome': 'LIMÃO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310138'},
        {'nome': 'MAMÃO FORMOSA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310175'},
        {'nome': 'MANDIOCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310143'},
        {'nome': 'MANGA PALMER KG', 'unidade_fracionada': 'KG', 'codigo_interno': '375054'},
        {'nome': 'MANGA TOMMY KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310144'},
        {'nome': 'MARACUJÁ KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310147'},
        {'nome': 'MELANCIA BABY KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322436'},
        {'nome': 'MELANCIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310148'},
        {'nome': 'UVA PRETA S SEMENTE 500G', 'unidade_fracionada': 'UN', 'codigo_interno': '368980'},
    ],
    "SÁBADO": [
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN', 'codigo_interno': '311283'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN', 'codigo_interno': '352544'},
        {'nome': 'ABOBORA KG BAIANA', 'unidade_fracionada': 'KG', 'codigo_interno': '310101'},
        {'nome': 'ABOBRINHA VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310103'},
        {'nome': 'ALHO EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310289'},
        {'nome': 'ALHO S CASCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310108'},
        {'nome': 'BATATA ASTERIX KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310214'},
        {'nome': 'BATATA BAROA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310114'},
        {'nome': 'BATATA DOCE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310115'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG', 'codigo_interno': '310119'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG', 'codigo_interno': '310173'},
        {'nome': 'BATATA YACON KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334978'},
        {'nome': 'BERINJELA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310121'},
        {'nome': 'BETERRABA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310122'},
        {'nome': 'CEBOLA BRANCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310125'},
        {'nome': 'CEBOLA ROXA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '334535'},
        {'nome': 'CENOURA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310126'},
        {'nome': 'CHUCHU KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310127'},
        {'nome': 'COUVE FLOR UN', 'unidade_fracionada': 'UN', 'codigo_interno': '313507'},
        {'nome': 'ERVILHA BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '310085'},
        {'nome': 'ERVILHA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310129'},
        {'nome': 'GENGIBRE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '322470'},
        {'nome': 'GOIABA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310130'},
        {'nome': 'INHAME KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310131'},
        {'nome': 'JILO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310132'},
        {'nome': 'LARANJA BAHIA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310134'},
        {'nome': 'LARANJA LIMA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310135'},
        {'nome': 'LARANJA PERA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310136'},
        {'nome': 'MANDIOCA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310143'},
        {'nome': 'MILHO VERDE BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '312655'},
        {'nome': 'MILHO VERDE ESPIGA', 'unidade_fracionada': 'UN', 'codigo_interno': '310153'},
        {'nome': 'MORANGA JAPONESA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310155'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN', 'codigo_interno': '324846'},
        {'nome': 'PEPINO JAPONES KG', 'unidade_fracionada': 'KG', 'codigo_interno': '345140'},
        {'nome': 'PEPINO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310154'},
        {'nome': 'PIMENTAO COLORIDO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '312952'},
        {'nome': 'PIMENTAO VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310160'},
        {'nome': 'QUIABO 300G', 'unidade_fracionada': 'UN', 'codigo_interno': '310161'},
        {'nome': 'REPOLHO ROXO KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310163'},
        {'nome': 'REPOLHO VERDE KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310162'},
        {'nome': 'TOMATE CEREJA 200G', 'unidade_fracionada': 'UN', 'codigo_interno': '310237'},
        {'nome': 'TOMATE EXTRA KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310165'},
        {'nome': 'VAGEM 250G', 'unidade_fracionada': 'UN', 'codigo_interno': '375105'},
        {'nome': 'VAGEM KG', 'unidade_fracionada': 'KG', 'codigo_interno': '310172'},
    ],
}