# produtos_config.py

PRODUTOS = {
    "SEGUNDA-FEIRA": [
        "ABACATE KG",
        "ABACAXI UNID. GRAUDO",
        "ABACAXI UNID. MEDIO",
        "AMEIXA IMPORTADA 500G",
        "AMEIXA KG IMPORTADA",
        "AMEIXA KG NACIONAL",
        "BANANA DA TERRA KG",
        "BANANA MACA KG",
        "BANANA NANICA KG",
        "BANANA OURO KG",
        "BANANA PRATA KG",
        "COCO SECO KG",
        "COCO VERDE",
        "GOIABA KG",
        "LARANJA BAHIA KG",
        "LARANJA LIMA KG",
        "LARANJA PERA KG",
        "LIMAO KG",
        "MACA ARGENTINA KG",
        "MACA FUJI KG",
        "MACA GALA NACIONAL KG",
        "MACA VERDE KG",
        "MAMAO AMAZONAS KG",
        "MAMAO FORMOSA KG",
        "MANGA PALMER KG",
        "MANGA TOMMY KG",
        "MANGA UBA KG",
        "MARACUJA KG",
        "MELANCIA BABY KG",
        "MELANCIA KG",
        "MELAO AMARELO KG",
        "MELAO REDINHA KG",
        "MELAO SAPIEL KG",
        "MEXERICA DEKOPON KG",
        "MEXERICA MORCOT KG",
        "MEXERICA PONKAN KG",
        "MEXERICA RIO KG",
        "MORANGO BDJ",
        "NECTARINA KG IMPORTADA",
        "NECTARINA KG NACIONAL",
        "PERA PORTUGUESA KG",
        "PERA WILLIAN KG",
        "PESSEGO BELLE FRUTA 600G",
        "PESSEGO IMPORTADO KG",
        "PESSEGO KG NACIONAL",
        "UVA ITALIA KG",
        "UVA NIAGARA 500G",
        "UVA NIAGARA KG",
        "UVA PRETA S SEMENTE 500G",
        "UVA RED GLOBE KG",
        "UVA RUBI KG",
        "UVA S/ SEMENTE KG",
        "UVA VERDE S/ SEMENTE 500G",
        "ATEMOIA KG",
        "CAJU 300G",
        "CAQUI 500G",
        "CAQUI KG",
        "CARAMBOLA KG",
        "CASTANHA PORTUGUESA KG",
        "CEREJA CHERRIES KG",
        "GRAVIOLA KG",
        "KIWI 500G",
        "KIWI KG",
        "LIMA DA PERSIA KG",
        "LIMAO SICILIANO KG",
        "NOZES C CASCA KG",
        "PITAYA KG",
        "SIRIGUELA 600G",
        "ALHO EXTRA KG",
        "ALHO S CASCA KG",
        "BATATA DOCE KG",
        "BATATA LAVADA KG EXTRA",
        "BATATA LAVADA KG MIUDA",
        "INHAME KG",
        "MANDIOCA KG",
        "MORANGA JAPONESA KG"
    ], # Produtos para o teste
    
    "TERÇA-FEIRA": [
        "ABACATE KG",
        "ABACAXI UNID. GRAUDO",
        "ABACAXI UNID. MEDIO",
        "AMEIXA IMPORTADA 500G",
        "AMEIXA KG IMPORTADA",
        "AMEIXA KG NACIONAL",
        "BANANA DA TERRA KG",
        "BANANA MACA KG",
        "BANANA NANICA KG",
        "BANANA OURO KG",
        "BANANA PRATA KG",
        "COCO SECO KG",
        "COCO VERDE",
        "GOIABA KG",
        "LARANJA BAHIA KG",
        "LARANJA LIMA KG",
        "LARANJA PERA KG",
        "LIMAO KG",
        "MACA ARGENTINA KG",
        "MACA FUJI KG",
        "MACA GALA NACIONAL KG",
        "MACA VERDE KG",
        "MAMAO AMAZONAS KG",
        "MAMAO FORMOSA KG",
        "MANGA PALMER KG",
        "MANGA TOMMY KG",
        "MANGA UBA KG",
        "MARACUJA KG",
        "MELANCIA BABY KG",
        "MELANCIA KG",
        "MELAO AMARELO KG",
        "MELAO REDINHA KG",
        "MELAO SAPIEL KG",
        "MEXERICA DEKOPON KG",
        "MEXERICA MORCOT KG",
        "MEXERICA PONKAN KG",
        "MEXERICA RIO KG",
        "MORANGO BDJ",
        "NECTARINA KG IMPORTADA",
        "NECTARINA KG NACIONAL",
        "PERA PORTUGUESA KG",
        "PERA WILLIAN KG",
        "PESSEGO BELLE FRUTA 600G",
        "PESSEGO IMPORTADO KG",
        "PESSEGO KG NACIONAL",
        "UVA ITALIA KG",
        "UVA NIAGARA 500G",
        "UVA NIAGARA KG",
        "UVA PRETA S SEMENTE 500G",
        "UVA RED GLOBE KG",
        "UVA RUBI KG",
        "UVA S/ SEMENTE KG",
        "UVA VERDE S/ SEMENTE 500G",
        "ATEMOIA KG",
        "CAJU 300G",
        "CAQUI 500G",
        "CAQUI KG",
        "CARAMBOLA KG",
        "CASTANHA PORTUGUESA KG",
        "CEREJA CHERRIES KG",
        "GRAVIOLA KG",
        "KIWI 500G",
        "KIWI KG",
        "LIMA DA PERSIA KG",
        "LIMAO SICILIANO KG",
        "NOZES C CASCA KG",
        "PITAYA KG",
        "SIRIGUELA 600G",
        "ALHO EXTRA KG",
        "ALHO S CASCA KG",
        "BATATA DOCE KG",
        "BATATA LAVADA KG EXTRA",
        "BATATA LAVADA KG MIUDA",
        "INHAME KG",
        "MANDIOCA KG",
        "MORANGA JAPONESA KG"
    ],
    
    "QUARTA-FEIRA": [
        "ABACAXI UNID. GRAUDO",
        "ABACAXI UNID. MEDIO",
        "GOIABA KG",
        "LARANJA BAHIA KG",
        "LARANJA LIMA KG",
        "LARANJA PERA KG",
        "MORANGO BDJ",
        "ABOBORA KG BAIANA",
        "ABOBRINHA VERDE KG",
        "ALHO EXTRA KG",
        "ALHO S CASCA KG",
        "BATATA ASTERIX KG",
        "BATATA BAROA KG",
        "BATATA DOCE KG",
        "BATATA LAVADA KG EXTRA",
        "BATATA LAVADA KG MIUDA",
        "BATATA YACON KG",
        "BERINJELA KG",
        "BETERRABA KG",
        "CEBOLA BRANCA KG",
        "CEBOLA ROXA KG",
        "CENOURA KG",
        "CHUCHU KG",
        "COUVE FLOR UN",
        "ERVILHA BDJ",
        "ERVILHA KG",
        "GENGIBRE KG",
        "INHAME KG",
        "JILO KG",
        "MANDIOCA KG",
        "MILHO VERDE BDJ",
        "MORANGA JAPONESESA KG",
        "PEPINO JAPONES KG",
        "PEPINO KG",
        "PIMENTAO COLORIDO KG",
        "PIMENTAO VERDE KG",
        "QUIABO 300G",
        "REPOLHO ROXO KG",
        "REPOLHO VERDE KG",
        "TOMATE CEREJA 200G",
        "TOMATE EXTRA KG",
        "VAGEM 250G",
        "VAGEM KG",
        "MILHO VERDE ESPIGA"
    ],
    
    "SEXTA-FEIRA": [
        "MELANCIA BABY KG",
        "MELANCIA KG",
        "ALHO EXTRA KG",
        "ALHO S CASCA KG",
        "BATATA ASTERIX KG",
        "BATATA DOCE KG",
        "BATATA LAVADA KG EXTRA",
        "BATATA LAVADA KG MIUDA",
        "ABACATE KG",
        "BANANA NANICA KG",
        "BANANA PRATA KG",
        "CAJU KG",
        "LARANJA PERA KG",
        "LIMÃO KG",
        "MAMÃO FORMOSA KG",
        "MANDIOCA KG",
        "MANGA PALMER KG",
        "MANGA TOMMY KG",
        "MARACUJÁ",
        "UVA VITÓRIA BANDEJA"
    ],
    
    "SÁBADO": [
        "ABACAXI UNID. GRAUDO",
        "ABACAXI UNID. MEDIO",
        "GOIABA KG",
        "LARANJA BAHIA KG",
        "LARANJA LIMA KG",
        "LARANJA PERA KG",
        "MORANGO BDJ",
        "ABOBORA KG BAIANA",
        "ABOBRINHA VERDE KG",
        "ALHO EXTRA KG",
        "ALHO S CASCA KG",
        "BATATA ASTERIX KG",
        "BATATA BAROA KG",
        "BATATA DOCE KG",
        "BATATA LAVADA KG EXTRA",
        "BATATA LAVADA KG MIUDA",
        "BATATA YACON KG",
        "BERINJELA KG",
        "BETERRABA KG",
        "CEBOLA BRANCA KG",
        "CEBOLA ROXA KG",
        "CENOURA KG",
        "CHUCHU KG",
        "COUVE FLOR UN",
        "ERVILHA BDJ",
        "ERVILHA KG",
        "GENGIBRE KG",
        "INHAME KG",
        "JILO KG",
        "MANDIOCA KG",
        "MILHO VERDE BDJ",
        "MORANGA JAPONESESA KG",
        "PEPINO JAPONES KG",
        "PEPINO KG",
        "PIMENTAO COLORIDO KG",
        "PIMENTAO VERDE KG",
        "QUIABO 300G",
        "REPOLHO ROXO KG",
        "REPOLHO VERDE KG",
        "TOMATE CEREJA 200G",
        "TOMATE EXTRA KG",
        "VAGEM 250G",
        "VAGEM KG",
        "MILHO VERDE ESPIGA"
    ],
}