# produtos_config.py

PRODUTOS = {
    "SEGUNDA-FEIRA": [
        {'nome': 'Maçã Fuji (Teste)', 'unidade_fracionada': 'KG'},
        {'nome': 'Banana Nanica (Teste)', 'unidade_fracionada': 'KG'},
        {'nome': 'Laranja Pera (Teste)', 'unidade_fracionada': 'KG'}
    ],
    
    "TERÇA-FEIRA": [
        {'nome': 'ABACATE', 'unidade_fracionada': 'KG'},
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN'},
        {'nome': 'AMEIXA IMPORTADA 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'AMEIXA KG IMPORTADA', 'unidade_fracionada': 'KG'},
        {'nome': 'AMEIXA KG NACIONAL', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA DA TERRA', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA MACA', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA NANICA', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA OURO', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA PRATA', 'unidade_fracionada': 'KG'},
        {'nome': 'COCO SECO', 'unidade_fracionada': 'KG'},
        {'nome': 'COCO VERDE', 'unidade_fracionada': 'UN'},
        {'nome': 'GOIABA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA BAHIA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA LIMA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA PERA', 'unidade_fracionada': 'KG'},
        {'nome': 'LIMAO', 'unidade_fracionada': 'KG'},
        {'nome': 'MACA ARGENTINA', 'unidade_fracionada': 'KG'},
        {'nome': 'MACA FUJI', 'unidade_fracionada': 'KG'},
        {'nome': 'MACA GALA NACIONAL', 'unidade_fracionada': 'KG'},
        {'nome': 'MACA VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'MAMAO AMAZONAS', 'unidade_fracionada': 'KG'},
        {'nome': 'MAMAO FORMOSA', 'unidade_fracionada': 'KG'},
        {'nome': 'MANGA PALMER', 'unidade_fracionada': 'KG'},
        {'nome': 'MANGA TOMMY', 'unidade_fracionada': 'KG'},
        {'nome': 'MANGA UBA', 'unidade_fracionada': 'KG'},
        {'nome': 'MARACUJA', 'unidade_fracionada': 'KG'},
        {'nome': 'MELANCIA BABY', 'unidade_fracionada': 'KG'},
        {'nome': 'MELANCIA', 'unidade_fracionada': 'KG'},
        {'nome': 'MELAO AMARELO', 'unidade_fracionada': 'KG'},
        {'nome': 'MELAO REDINHA', 'unidade_fracionada': 'KG'},
        {'nome': 'MELAO SAPIEL', 'unidade_fracionada': 'KG'},
        {'nome': 'MEXERICA DEKOPON', 'unidade_fracionada': 'KG'},
        {'nome': 'MEXERICA MORCOT', 'unidade_fracionada': 'KG'},
        {'nome': 'MEXERICA PONKAN', 'unidade_fracionada': 'KG'},
        {'nome': 'MEXERICA RIO', 'unidade_fracionada': 'KG'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'NECTARINA KG IMPORTADA', 'unidade_fracionada': 'KG'},
        {'nome': 'NECTARINA KG NACIONAL', 'unidade_fracionada': 'KG'},
        {'nome': 'PERA PORTUGUESA', 'unidade_fracionada': 'KG'},
        {'nome': 'PERA WILLIAN', 'unidade_fracionada': 'KG'},
        {'nome': 'PESSEGO BELLE FRUTA 600G', 'unidade_fracionada': 'UN'},
        {'nome': 'PESSEGO IMPORTADO', 'unidade_fracionada': 'KG'},
        {'nome': 'PESSEGO KG NACIONAL', 'unidade_fracionada': 'KG'},
        {'nome': 'UVA ITALIA', 'unidade_fracionada': 'KG'},
        {'nome': 'UVA NIAGARA 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA NIAGARA', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA PRETA S SEMENTE 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA RED GLOBE', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA RUBI', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA S/ SEMENTE', 'unidade_fracionada': 'UN'},
        {'nome': 'UVA VERDE S/ SEMENTE 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'ATEMOIA', 'unidade_fracionada': 'KG'},
        {'nome': 'CAJU 300G', 'unidade_fracionada': 'UN'},
        {'nome': 'CAQUI 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'CAQUI', 'unidade_fracionada': 'KG'},
        {'nome': 'CARAMBOLA', 'unidade_fracionada': 'KG'},
        {'nome': 'CASTANHA PORTUGUESA', 'unidade_fracionada': 'KG'},
        {'nome': 'CEREJA CHERRIES', 'unidade_fracionada': 'KG'},
        {'nome': 'GRAVIOLA', 'unidade_fracionada': 'KG'},
        {'nome': 'KIWI 500G', 'unidade_fracionada': 'UN'},
        {'nome': 'KIWI', 'unidade_fracionada': 'KG'},
        {'nome': 'LIMA DA PERSIA', 'unidade_fracionada': 'KG'},
        {'nome': 'LIMAO SICILIANO', 'unidade_fracionada': 'KG'},
        {'nome': 'NOZES C CASCA', 'unidade_fracionada': 'KG'},
        {'nome': 'PITAYA', 'unidade_fracionada': 'KG'},
        {'nome': 'SIRIGUELA 600G', 'unidade_fracionada': 'UN'},
        {'nome': 'ALHO EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO S CASCA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA DOCE', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG'},
        {'nome': 'INHAME', 'unidade_fracionada': 'KG'},
        {'nome': 'MANDIOCA', 'unidade_fracionada': 'KG'},
        {'nome': 'MORANGA JAPONESA', 'unidade_fracionada': 'KG'},
    ],
    
    "QUARTA-FEIRA": [
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN'},
        {'nome': 'GOIABA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA BAHIA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA LIMA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA PERA', 'unidade_fracionada': 'KG'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'ABOBORA KG BAIANA', 'unidade_fracionada': 'KG'},
        {'nome': 'ABOBRINHA VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO S CASCA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA ASTERIX', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA BAROA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA DOCE', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA YACON', 'unidade_fracionada': 'KG'},
        {'nome': 'BERINJELA', 'unidade_fracionada': 'KG'},
        {'nome': 'BETERRABA', 'unidade_fracionada': 'KG'},
        {'nome': 'CEBOLA BRANCA', 'unidade_fracionada': 'KG'},
        {'nome': 'CEBOLA ROXA', 'unidade_fracionada': 'KG'},
        {'nome': 'CENOURA', 'unidade_fracionada': 'KG'},
        {'nome': 'CHUCHU', 'unidade_fracionada': 'KG'},
        {'nome': 'COUVE FLOR UN', 'unidade_fracionada': 'UN'},
        {'nome': 'ERVILHA BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'ERVILHA', 'unidade_fracionada': 'KG'},
        {'nome': 'GENGIBRE', 'unidade_fracionada': 'KG'},
        {'nome': 'INHAME', 'unidade_fracionada': 'KG'},
        {'nome': 'JILO', 'unidade_fracionada': 'KG'},
        {'nome': 'MANDIOCA', 'unidade_fracionada': 'KG'},
        {'nome': 'MILHO VERDE BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'MORANGA JAPONESA', 'unidade_fracionada': 'KG'},
        {'nome': 'PEPINO JAPONES', 'unidade_fracionada': 'KG'},
        {'nome': 'PEPINO', 'unidade_fracionada': 'KG'},
        {'nome': 'PIMENTAO COLORIDO', 'unidade_fracionada': 'KG'},
        {'nome': 'PIMENTAO VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'QUIABO 300G', 'unidade_fracionada': 'UN'},
        {'nome': 'REPOLHO ROXO', 'unidade_fracionada': 'KG'},
        {'nome': 'REPOLHO VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'TOMATE CEREJA 200G', 'unidade_fracionada': 'UN'},
        {'nome': 'TOMATE EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'VAGEM 250G', 'unidade_fracionada': 'UN'},
        {'nome': 'VAGEM', 'unidade_fracionada': 'KG'},
        {'nome': 'MILHO VERDE ESPIGA', 'unidade_fracionada': 'UN'}
    ],
    
    "SEXTA-FEIRA": [
        {'nome': 'MELANCIA BABY', 'unidade_fracionada': 'KG'},
        {'nome': 'MELANCIA', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO S CASCA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA ASTERIX', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA DOCE', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG'},
        {'nome': 'ABACATE', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA NANICA', 'unidade_fracionada': 'KG'},
        {'nome': 'BANANA PRATA', 'unidade_fracionada': 'KG'},
        {'nome': 'CAJU', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA PERA', 'unidade_fracionada': 'KG'},
        {'nome': 'LIMÃO', 'unidade_fracionada': 'KG'},
        {'nome': 'MAMÃO FORMOSA', 'unidade_fracionada': 'KG'},
        {'nome': 'MANDIOCA', 'unidade_fracionada': 'KG'},
        {'nome': 'MANGA PALMER', 'unidade_fracionada': 'KG'},
        {'nome': 'MANGA TOMMY', 'unidade_fracionada': 'KG'},
        {'nome': 'MARACUJÁ', 'unidade_fracionada': 'KG'},
        {'nome': 'UVA VITÓRIA BANDEJA', 'unidade_fracionada': 'UN'}
    ],
    
    "SÁBADO": [
        {'nome': 'ABACAXI UNID. GRAUDO', 'unidade_fracionada': 'UN'},
        {'nome': 'ABACAXI UNID. MEDIO', 'unidade_fracionada': 'UN'},
        {'nome': 'GOIABA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA BAHIA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA LIMA', 'unidade_fracionada': 'KG'},
        {'nome': 'LARANJA PERA', 'unidade_fracionada': 'KG'},
        {'nome': 'MORANGO BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'ABOBORA KG BAIANA', 'unidade_fracionada': 'KG'},
        {'nome': 'ABOBRINHA VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'ALHO S CASCA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA ASTERIX', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA BAROA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA DOCE', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA LAVADA KG MIUDA', 'unidade_fracionada': 'KG'},
        {'nome': 'BATATA YACON', 'unidade_fracionada': 'KG'},
        {'nome': 'BERINJELA', 'unidade_fracionada': 'KG'},
        {'nome': 'BETERRABA', 'unidade_fracionada': 'KG'},
        {'nome': 'CEBOLA BRANCA', 'unidade_fracionada': 'KG'},
        {'nome': 'CEBOLA ROXA', 'unidade_fracionada': 'KG'},
        {'nome': 'CENOURA', 'unidade_fracionada': 'KG'},
        {'nome': 'CHUCHU', 'unidade_fracionada': 'KG'},
        {'nome': 'COUVE FLOR UN', 'unidade_fracionada': 'UN'},
        {'nome': 'ERVILHA BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'ERVILHA', 'unidade_fracionada': 'KG'},
        {'nome': 'GENGIBRE', 'unidade_fracionada': 'KG'},
        {'nome': 'INHAME', 'unidade_fracionada': 'KG'},
        {'nome': 'JILO', 'unidade_fracionada': 'KG'},
        {'nome': 'MANDIOCA', 'unidade_fracionada': 'KG'},
        {'nome': 'MILHO VERDE BDJ', 'unidade_fracionada': 'UN'},
        {'nome': 'MORANGA JAPONESA', 'unidade_fracionada': 'KG'},
        {'nome': 'PEPINO JAPONES', 'unidade_fracionada': 'KG'},
        {'nome': 'PEPINO', 'unidade_fracionada': 'KG'},
        {'nome': 'PIMENTAO COLORIDO', 'unidade_fracionada': 'KG'},
        {'nome': 'PIMENTAO VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'QUIABO 300G', 'unidade_fracionada': 'UN'},
        {'nome': 'REPOLHO ROXO', 'unidade_fracionada': 'KG'},
        {'nome': 'REPOLHO VERDE', 'unidade_fracionada': 'KG'},
        {'nome': 'TOMATE CEREJA 200G', 'unidade_fracionada': 'UN'},
        {'nome': 'TOMATE EXTRA', 'unidade_fracionada': 'KG'},
        {'nome': 'VAGEM 250G', 'unidade_fracionada': 'UN'},
        {'nome': 'VAGEM', 'unidade_fracionada': 'KG'},
        {'nome': 'MILHO VERDE ESPIGA', 'unidade_fracionada': 'UN'}
    ],
}